### ISSUE TITLE
Promotions link is broken

### ISSUE THREAD

**Issue by upkarlidder** [shaileshpendkar/selia-adminpanel#1]
The promotions link is broken
http://54.68.130.70/comingsoon

It should point to
http://54.68.130.70/adminpanel/public/comingsoon

**Comment by shaileshpendkar** [comment]
sub domains not yet created on dev hence using 2 apps and web site with one document root. This is the result of that. in Prod there will be 3 sub domians hence store manager doc root will be /adminpanel/public making the existing link in code to work
